prjFunShare_Core/Areas/backend/ViewModels/LoginViewModel.cs
using Microsoft.AspNetCore.Mvc;

namespace prjFunShare_Core.Areas.backend.ViewModels
{
    public class LoginViewModel
    {
        public string txtAccount { get; set; }
        public string txtPassword { get; set; }
    }
}

prjFunShare_Core/Areas/backend/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using prjFunShare_Core.Models;
using prjFunShare_Core.Areas.backend.ViewModels;
using System.Text.Json;

namespace prjFunShare_Core.Areas.backend.Controllers
{
    [Area("backend")]
    public class ManagerController : Controller
    {
        private readonly ILogger<ManagerController> _logger;
        private readonly prjFunShare_Core.Models.FUNShareContext _context;
        private readonly IConfiguration _config;

        public ManagerController(ILogger<ManagerController> logger, prjFunShare_Core.Models.FUNShareContext c, IConfiguration config)
        {
            _logger = logger;
            _context = c;
            _config = config;
        }

        public IActionResult Index()
        {//區分登入身分
         //供應商
         //if (HttpContext.Session.Keys.Contains(CDictionary.SK_LOGINED_SUPPLIER))
         //{
         //string json = HttpContext.Session.GetString(CDictionary.SK_LOGINED_SUPPLIER);
         //Supplier supplier = JsonSerializer.Deserialize<Supplier>(json);
            Supplier supplier = _context.Supplier.Find(1);
            string sender = "sender";
            Response.Cookies.Append(sender, "S" + supplier.SupplierId.ToString());
            CIndexInfoViewModel vm = new CIndexInfoViewModel();
                vm.Supplier = supplier;
                vm.ProductOnSaleCount = _context.Product.Where(x => x.SupplierId == supplier.SupplierId && x.StatusId == 12).Count();
                vm.ProductCount = _context.Product.Where(x => x.SupplierId == supplier.SupplierId).Count();
                vm.OrderCount = _context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId).Count();
                vm.OrderAmount = (decimal)_context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId).Select(x => x.ProductDetail.UnitPrice).Sum();
                //月營收成長率 =（當月營收 – 上月營收）÷ 上月營收 x 100%
                var lastMonthSales = _context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId
                                                                             && x.Order.OrderTime.Year == DateTime.Now.Year && x.Order.OrderTime.Month == (DateTime.Now.Month - 1))
                                                                             .Select(x => x.ProductDetail.UnitPrice).Sum();
                var thisMonthSales = _context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId
                                                                 && x.Order.OrderTime.Year == DateTime.Now.Year && x.Order.OrderTime.Month == DateTime.Now.Month)
                                                                 .Select(x => x.ProductDetail.UnitPrice).Sum();
                if (lastMonthSales != 0)
                    vm.MoM = (decimal)((thisMonthSales - lastMonthSales) / lastMonthSales);
                else
                    vm.MoM = 0;
                //年營收成長率
                var lastYearSales = _context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId
                                                                                                        && x.Order.OrderTime.Year == DateTime.Now.Year - 3) //倒出來的數字比較好看
                                                                                                                .Select(x => x.ProductDetail.UnitPrice).Sum();
                var thisYearSales = _context.OrderDetail.Where(x => x.ProductDetail.Product.SupplierId == supplier.SupplierId
                                                                                                        && x.Order.OrderTime.Year == DateTime.Now.Year - 2)
                                                                                                                .Select(x => x.ProductDetail.UnitPrice).Sum();
                if (lastYearSales != 0)
                    vm.YoY = (decimal)((thisYearSales - lastYearSales) / lastYearSales);
                else
                    vm.YoY = 0;

                return View(vm);
            //}
            //// Admin
            //else if (HttpContext.Session.Keys.Contains(CDictionary.SK_LOGINED_ADMIN))
            //{
            //    CIndexInfoViewModel vm = new CIndexInfoViewModel();
            //    vm.ProductOnSaleCount = _context.Product.Where(x => x.StatusId == 12).Count();
            //    vm.ProductCount = _context.Product.Count();
            //    vm.OrderCount = _context.OrderDetail.Count();
            //    vm.OrderAmount = (decimal)_context.OrderDetail.Select(x => x.ProductDetail.UnitPrice).Sum();
            //    //月營收成長率 =（當月營收 – 上月營收）÷ 上月營收 x 100%
            //    var lastMonthSales = _context.OrderDetail.Where(x => x.Order.OrderTime.Year == DateTime.Now.Year
            //                                                                                                    && x.Order.OrderTime.Month == (DateTime.Now.Month - 1))
            //                                                                 .Select(x => x.ProductDetail.UnitPrice).Sum();
            //    var thisMonthSales = _context.OrderDetail.Where(x => x.Order.OrderTime.Year == DateTime.Now.Year
            //                                                                                                   && x.Order.OrderTime.Month == DateTime.Now.Month)
            //                                                                 .Select(x => x.ProductDetail.UnitPrice).Sum();
            //    if (lastMonthSales != 0)
            //        vm.MoM = (decimal)((thisMonthSales - lastMonthSales) / lastMonthSales);
            //    else
            //        vm.MoM = 0;
            //    //年營收成長率
            //    var lastYearSales = _context.OrderDetail.Where(x => x.Order.OrderTime.Year == DateTime.Now.Year - 3) //倒出來的數字比較好看
            //                                                                                                    .Select(x => x.ProductDetail.UnitPrice).Sum();
            //    var thisYearSales = _context.OrderDetail.Where(x => x.Order.OrderTime.Year == DateTime.Now.Year - 2)
            //                                                                 .Select(x => x.ProductDetail.UnitPrice).Sum();
            //    if (lastYearSales != 0)
            //        vm.YoY = (decimal)((thisYearSales - lastYearSales) / lastYearSales);
            //    else
            //        vm.YoY = 0;

            //    return View(vm);
            //}

            //未登入
            //return RedirectToAction("Login");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(LoginViewModel vm)
        {
            //管理員登入
            string adminId = _config["Admin:Id"];
            string adminPassword = _config["Admin:Password"];

            if (adminId.Equals(vm.txtAccount) && adminPassword.Equals(vm.txtPassword))
            {
                HttpContext.Session.SetString(CDictionary.SK_LOGINED_ADMIN, "Admin");
                // 刪除廠商登入資料
                HttpContext.Session.Remove(CDictionary.SK_LOGINED_SUPPLIER);

                return RedirectToAction("Index");
            }
            //廠商登入
            Supplier sup = _context.Supplier.FirstOrDefault(
                t => t.TaxId.Equals(vm.txtAccount) && t.Password.Equals(vm.txtPassword));
            if (sup != null && sup.Password.Equals(vm.txtPassword))
            {
                string json = JsonSerializer.Serialize(sup);
                HttpContext.Session.SetString(CDictionary.SK_LOGINED_SUPPLIER, json);
                // 刪除管理員登入資料
                HttpContext.Session.Remove(CDictionary.SK_LOGINED_ADMIN);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Login");
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Remove(CDictionary.SK_LOGINED_SUPPLIER);
            HttpContext.Session.Remove(CDictionary.SK_LOGINED_ADMIN);
            return RedirectToAction("Index");
        }
        public IActionResult Register()
        {
            IEnumerable<City> cities = _context.City.ToList();
            ViewBag.Cities = new SelectList(cities, "CityId", "CityName");
            return View();
        }
        [HttpPost]
        public IActionResult Register(Supplier supl)
        {
            City selectedCity = _context.City.Find(supl.CityId);

            if (selectedCity != null)
            {
                supl.StatusId = 16;
                supl.City = selectedCity;
            }
            _context.Supplier.Add(supl);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

prjFunShare_Core/Areas/backend/Views/Manager/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登入</title>
    <!-- FunShare icon -->
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.4.2/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
    <main class="form-signin" style="margin:auto" width=40%>

        <img src="~/img/funsharelogo.svg" width="100%" />
        <form method="post" class="row g-3 needs-validation" novalidate>
            <div class="col-md-12">
                <div class="form-outline">
                    <input type="text" class="form-control" id="Account" name="txtAccount" required />
                    <label for="Account" class="form-label">請輸入統一編號</label>
                    <div class="invalid-feedback">請輸入統一編號</div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-outline">
                    <input type="password" class="form-control" id="Password" name="txtPassword" required />
                    <label for="Password" class="form-label">密碼</label>
                    <i id="checkEye" class="fas fa-eye"></i>
                </div>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <input type="submit" value="登入" class="btn btn-primary" />
                <input id="btnDemo" type="button" value="廠商" class="btn btn-danger ms-2" />
                <input id="btnDemoForAdmin" type="button" value="管理員" class="btn btn-warning ms-2" />
            </div>
            <div class="form-group" style="text-align: center">
                @Html.ActionLink("忘記密碼", "ForgetPassword", "Manager", null, null)
            </div>
            <hr class="flex-xxl-shrink-1" style="text-align: center; width: 100%" />
            <div class="form-group" style="text-align: center">
                @Html.ActionLink("註冊", "Register", "Manager", null, new { @class = "btn btn-secondary" })
            </div>
        </form>
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $('#btnDemo').on('click', function () {
            $('#Password').addClass('active');
            $('#Account').addClass('active');
            $('#Password').val(1234);
            $('#Account').val('98270077');
        })
        $('#btnDemoForAdmin').on('click', function () {
            $('#Password').addClass('active');
            $('#Account').addClass('active');
            $('#Password').val(987654321);
            $('#Account').val('FUNShare');
        })
        $("#checkEye").click(function () {
            if ($(this).hasClass('fa-eye')) {
                $("#Password").attr('type', 'text');
            } else {
                $("#Password").attr('type', 'password');
            }
            $(this).toggleClass('fa-eye').toggleClass('fa-eye-slash');
        });
    </script>
</body>
</html>

prjFunShare_Core/Areas/backend/Views/Manager/Register.cshtml
@model prjFunShare_Core.Models.Supplier
@{
    ViewData["Title"] = "Register";
    ViewBag.Action = "SupplierList";
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登入</title>
    <!-- FunShare icon -->
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.4.2/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="container">
        <h1 class="text-center">歡迎加入FunShare</h1>

        <hr />
        <div class="row justify-content-center">
            <div class="col-md-4">
                <form asp-action="Register">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="TaxId" class="control-label">統一編號</label>
                        <input asp-for="TaxId" class="form-control" />
                        <span asp-validation-for="TaxId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SupplierName" class="control-label">供應商名稱</label>
                        <input asp-for="SupplierName" class="form-control" />
                        <span asp-validation-for="SupplierName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SupplierPhone" class="control-label">連絡電話</label>
                        <input asp-for="SupplierPhone" class="form-control" />
                        <span asp-validation-for="SupplierPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label">電子郵件</label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CityId" class="control-label">城市</label>
                        <select asp-for="CityId" class="form-control" asp-items="@ViewBag.Cities"></select>@*在後面藏選擇的編號*@
                        <span asp-validation-for="CityId" class="text-danger"></span>
                    </div>

                    @*                 <div class="form-group">
                    <label asp-for="SupplierPhoto" class="control-label">供應商圖片</label>
                    <input asp-for="SupplierPhoto" class="form-control" />
                    <span asp-validation-for="SupplierPhoto" class="text-danger"></span>
                    </div> *@
                    <div class="form-group">
                        <label asp-for="Fax" class="control-label">傳真</label>
                        <input asp-for="Fax" class="form-control" />
                        <span asp-validation-for="Fax" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label">密碼</label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactPerson" class="control-label">聯繫人</label>
                        <input asp-for="ContactPerson" class="form-control" />
                        <span asp-validation-for="ContactPerson" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LogoImage" class="control-label">供應商圖片</label>
                        <input asp-for="LogoImage" class="form-control" />
                        <span asp-validation-for="LogoImage" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label">詳細資料</label>
                        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label for="formFile" class="form-label">檔案上傳</label>
                        <input class="form-control" type="file" id="formFile" name="file">
                    </div>
                    <img id="imagePreview" src="#" alt="圖片預覽" style="max-width: 100%; max-height: 200px;">

                    <div class="form-group">
                        <input type="submit" value="送出並加入我們" class="btn btn-primary" />
                    </div>
                </form>
            </div>

        </div>
    </div>


    <script>
        //導入 ASP.NET Core MVC 的驗證腳本，這些腳本用於處理客戶端的表單驗證。
        // ASP.NET Core MVC 的表單驗證可以確保用戶輸入的資料符合指定的規則和格式，從而減少輸入錯誤和無效的資料提交到伺服器端。
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        // 用來顯示圖片預覽
        document.getElementById("formFile").addEventListener("change", function () {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.getElementById("imagePreview").src = e.target.result;
            };
            reader.readAsDataURL(this.files[0]);
        });
    </script>

</body>
</html>