prjFunShare_backend/Controllers/ManagerCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjFunShare_backend.Models;
using prjFunShare_backend.ViewModels;
using Microsoft.Extensions.Hosting;




namespace prjFunShare_backend.Controllers
{
    public class ManagerCustomerController : Controller
    {
        private readonly FUNShareContext _context;
        IEnumerable<CustomerInfomation> datas = null;
        private readonly IWebHostEnvironment _host;
        public ManagerCustomerController(FUNShareContext c, IWebHostEnvironment host)
        {
            _context = c;
            _host = host;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List(CKeywordViewModel vm)
        {
            //to do:在 ASP.NET MVC 應用程式中，使用 Entity Framework 新增排序、篩選和分頁 https://learn.microsoft.com/zh-tw/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application
            
           
            if (string.IsNullOrEmpty(vm.txtKeyword))
            {
                datas = from cust in _context.CustomerInfomation.Include(d => d.District).Include(s => s.Status)
                        select cust;
            }
            else
                datas = _context.CustomerInfomation.Include(d => d.District).Include(s => s.Status).Where(cust => cust.Name.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    || cust.PhoneNumber.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    || cust.Email.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    || cust.ResidentId.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    || cust.District.DistrictName.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    || cust.Status.Description.ToUpper().Contains(vm.txtKeyword.ToUpper())
                    );
            return View(datas);
        }

        public IActionResult ReverseStatus(int id)
        {
            if (id == null)
                return RedirectToAction("List");
            CustomerInfomation c = _context.CustomerInfomation.Find(id);
            c.StatusId = 1;
            c.SuspensionReason = "";
            _context.Update(c);
            _context.SaveChanges();

            return RedirectToAction("List");
        }
        public IActionResult ChangeStatus(int id)
        {
            if (id == null)
                return RedirectToAction("List");
            CustomerInfomation cust = _context.CustomerInfomation.Find(id);
            CustomerInfomationWrap custWrap = new CustomerInfomationWrap();
            custWrap.CustomerInfomation = cust;
            return View(custWrap);
        }
        [HttpPost]
        public IActionResult ChangeStatus(CustomerInfomationWrap cust)
        {

            if (cust != null)
            {
                CustomerInfomation c = _context.CustomerInfomation.Find(cust.MemberId);
                c.StatusId = 3;
                c.SuspensionReason = cust.SuspensionReason;
                _context.Update(c);
                _context.SaveChanges();
            }

            return RedirectToAction("List");
        }
        public IActionResult Create()
        {
            ViewData["DisctrictId"] = new SelectList(_context.District, "DistrictId", "DistrictName");
            ViewData["StatusId"] = new SelectList(_context.Status.Where(s => s.StatusType.Equals("Customer_Infomation")), "StatusId", "Description");

            return View();
        }
        [HttpPost]
        public IActionResult Create(CustomerInfomation cust, IFormFile file)
        {
            
            if (file != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    file.CopyTo(memoryStream);
                    cust.Photo = memoryStream.ToArray();
                }
            }
            cust.StatusId = 2;
            _context.CustomerInfomation.Add(cust);
            _context.SaveChanges();
            
            return RedirectToAction("List");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");           

            CustomerInfomation cust = _context.CustomerInfomation.Find(id);
            ViewData["DisctrictId"] = new SelectList(_context.District, "DistrictId", "DistrictName", cust.DistrictId);
            ViewData["StatusId"] = new SelectList(_context.Status.Where(s => s.StatusType.Equals("Customer_Infomation")), "StatusId", "Description", cust.StatusId);

            if (cust == null)
                return RedirectToAction("List");
            CustomerInfomationWrap custwrap = new CustomerInfomationWrap();
            custwrap.CustomerInfomation = cust;
            return View(custwrap);
        }
        [HttpPost]
        public IActionResult Edit(CustomerInfomation pIn, IFormFile file)
        {

            
            CustomerInfomation cust = _context.CustomerInfomation.Find(pIn.MemberId);
            if (cust != null)
                {
                if (file != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        file.CopyTo(memoryStream);
                        cust.Photo = memoryStream.ToArray();
                    }
                }
                cust.ResidentId = pIn.ResidentId;               
                cust.ParentId =pIn.ParentId;
                cust.Name = pIn.Name;                
                cust.Gender = pIn.Gender;
                cust.DistrictId = pIn.DistrictId;
                cust.Address = pIn.Address;
                cust.BirthDate = pIn.BirthDate;
                cust.Nickname = pIn.Nickname;
                cust.IsAllergy = pIn.IsAllergy;
                cust.AllergyDescription = pIn.AllergyDescription;
                cust.Note = pIn.Note;
                cust.StatusId = pIn.StatusId;                
                cust.SuspensionReason = pIn.SuspensionReason;
                
                _context.SaveChanges();

            }
            return RedirectToAction("List");
        }

        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
              
                CustomerInfomation cust = _context.CustomerInfomation.Find(id);
                if (cust != null)
                {
                    _context.CustomerInfomation.Remove(cust);
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }
    }
}

prjFunShare_backend/Views/ManagerCustomer/ChangeStatus.cshtml
@model prjFunShare_backend.Models.CustomerInfomationWrap

@{
    ViewData["Title"] = "停權";
}


<h1>停權</h1>

<h4>停權資訊</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ChangeStatus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <input asp-for="MemberId" class="form-control" />
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div> *@
           @*  <div class="form-group">
                <label asp-for="ResidentId" class="control-label"></label>
                <input asp-for="ResidentId" class="form-control" readonly disabled />
                <span asp-validation-for="ResidentId" class="text-danger"></span>
            </div>   *@         
            <input asp-for="MemberId" class="form-control" type="hidden" />
            @* <input asp-for="StatusId" value="3" class="form-control" type="hidden" /> *@
                
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly disabled />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="SuspensionReason" class="control-label"></label>
                <input asp-for="SuspensionReason" class="form-control" />
                <span asp-validation-for="SuspensionReason" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input id="btnSubmit" type="submit" value="停權" class="btn btn-outline-danger" />
                <a class="btn btn-outline-primary" type="button" asp-action="List">回上一頁</a>
                <input id="btnDemo" type="button" value="DEMO1" class="btn btn-outline-danger" />
               @*  <input id="btnDemo2" type="button" value="DEMO2" class="btn btn-danger" /> *@
            </div>
        </form>
    </div>
</div>
<br/>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} 
            
    
    <script>

        // $('#btnDemo1').on('click', function () {
        //     $('#SuspensionReason').addClass('active');
        //     $('#SuspensionReason').val('無故缺席五次以上');
        // })
        $('#btnDemo').on('click', function () {
            $('#SuspensionReason').addClass('active');
            $('#SuspensionReason').val('積欠貨款，態度不佳。');
        })
        // document.getElementById("#btnSubmit").addEventListener("click", function () {
        //     swal( "停權", "你確定嗎?", "success",{ button: "確定!" })
        // }).then(function (){ location.href = "@Url.Action("List","ManagerCustomer")";
        // })
    </script>

}

prjFunShare_backend/Views/ManagerCustomer/Create.cshtml
@model prjFunShare_backend.Models.CustomerInfomationWrap

@{
    ViewData["Title"] = "新增會員";
}

<h1>新增會員</h1>
<p align="right">
    <a class="btn btn-outline-primary" type="button" asp-action="List">回上一頁</a>
</p>

<h4>會員資料</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" id="formCreate" method="POST" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
            <label asp-for="MemberId" class="control-label"></label>
            <input asp-for="MemberId" class="form-control" />
            <span asp-validation-for="MemberId" class="text-danger"></span>
            </div> *@
            <div class="row">
                <div class="col-md-3">
                    <input asp-for="StatusId" value="2" hidden />
                    <div class="form-group ">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" id="Photo" name="file" class="form-control" type="file" accept="image/*" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                        <br />
                        <img class="img-fluid rounded-start" id="previewImg" src="~/img/預設頭像.jpg" />
                    </div>

                </div>
                <div class="col-md-4">

                    <div class="form-group col ">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="BirthDate" class="control-label"></label>
                        <input asp-for="BirthDate" class="form-control" />
                        <span asp-validation-for="BirthDate" class="text-danger"></span>
                    </div>


                    <div class="form-group col">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="ResidentId" class="control-label"></label>
                        <input asp-for="ResidentId" class="form-control" />
                        <span asp-validation-for="ResidentId" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-5">

                    <div class="form-group col">
                        <label asp-for="Nickname" class="control-label"></label>
                        <input asp-for="Nickname" class="form-control" />
                        <span asp-validation-for="Nickname" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="ParentId" class="control-label">家長姓名</label>
                        <input asp-for="ParentId" class="form-control" />
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>

                    <div class="form-group row-cols">
                        <label asp-for="DistrictId" class="control-label">行政區</label>
                        <select asp-for="DistrictId" class="form-control" asp-items="ViewBag.DisctrictId"></select>
                        <span asp-validation-for="DistrictId" class="text-danger"></span>
                    </div>
                    <div class="form-group row-cols">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                    <div class="form-group form-check col-sm-2">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsAllergy" /> @Html.DisplayNameFor(model => model.IsAllergy)
                        </label>
                    </div>
                    <div class="form-group col-sm-10">
                        <label asp-for="AllergyDescription" class="control-label"></label>
                        <input asp-for="AllergyDescription" class="form-control" />
                        <span asp-validation-for="AllergyDescription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Note" class="control-label"></label>
                        <textarea asp-for="Note" class="form-control"></textarea>
                        <span asp-validation-for="Note" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="新增並儲存" id="btnCreate" class="btn btn-primary" />
                <input type="button" value="DEMO" id="btnDemo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</br>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
@section Scripts {
    <script>
        
        $('#btnDemo').on('click', function () {
            $('#ResidentId').addClass('active');
            $('#ResidentId').val('Lucy Hsieh');
            $('#Name').addClass('active');
            $('#Name').val('Lucy Hsieh');
            $('#Gender').addClass('active');
            $('#Gender').val('F');
            $('#PhoneNumber').addClass('active');
            $('#PhoneNumber').val('0988123456');
            $('#Email').addClass('active');
            $('#Email').val('LucyHsieh@gmail.com');
            $('#Email').addClass('active');
            $('#Email').val('LucyHsieh@gmail.com');            
            $('#DistrictId').addClass('active');
            $('#DistrictId').val('10');
            $('#Address').addClass('active');
            $('#Address').val('中山北路');
            $('#BirthDate').addClass('active');
            $('#BirthDate').val('1999-09-09');
            $('#Nickname').addClass('active');
            $('#Nickname').val('L.H.');
            $('#Password').addClass('active');
            $('#Password').val('123456');  
            $('#Note').addClass('active');
            $('#Note').val('Note');
        })

        "use strict";

        function AJAXSubmit(oFormElement) {
            var oReq = new XMLHttpRequest();
            oReq.onload = function (e) {
                oFormElement.elements.nameItem("result").value =
                    'Result:' + this.status + '' + this.statusText;
            };
            oReq.open("post", oFormElement.action);
            oReg.send(new FormData(oFormElement));
        }

        $("#Photo").change(function () {
            //當檔案改變後，做一些事
            readURL(this);   // this代表<input id="formFile">
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#previewImg").attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

    </script>
}

prjFunShare_backend/Views/ManagerCustomer/Edit.cshtml
@model prjFunShare_backend.Models.CustomerInfomationWrap

@{
    ViewData["Title"] = "會員資料編輯";
}

<h1>會員資料編輯</h1>


<h4>會員資料</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" id="formEdit" method="POST" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="MemberID" value="@Model.MemberId" />
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" class="form-control" id="Photo" type="file" accept="image/*" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                        <br />
                        @if (Model.Photo != null)
                        {
                            <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Photo)" id="preview-image" style="width:160px" />
                        }
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group col">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="ResidentId" class="control-label"></label>
                        <input asp-for="ResidentId" class="form-control" />
                        <span asp-validation-for="ResidentId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="BirthDate" class="control-label"></label>
                        <input asp-for="BirthDate" class="form-control" />
                        <span asp-validation-for="BirthDate" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="StatusId" class="control-label">狀態</label>
                        <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                        <span asp-validation-for="StatusId" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-5">

                    <div class="form-group col">
                        <label asp-for="Nickname" class="control-label"></label>
                        <input asp-for="Nickname" class="form-control" />
                        <span asp-validation-for="Nickname" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="ParentId" class="control-label">家長姓名</label>
                        <input asp-for="ParentId" class="form-control" />
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="DistrictId" class="control-label">行政區</label>
                        <select asp-for="DistrictId" class="form-control" asp-items="ViewBag.DisctrictId"></select>
                        <span asp-validation-for="DistrictId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                    <div class="form-group form-check ">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsAllergy" /> @Html.DisplayNameFor(model => model.IsAllergy)
                        </label>
                    </div>
                    <div class="form-group ">
                        <label asp-for="AllergyDescription" class="control-label"></label>
                        <input asp-for="AllergyDescription" class="form-control" />
                        <span asp-validation-for="AllergyDescription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Note" class="control-label"></label>
                        <textarea asp-for="Note" class="form-control"></textarea>
                        <span asp-validation-for="Note" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="更新並儲存" id="btnEdit" class="btn btn-outline-primary" />
                <a class="btn btn-outline-primary" type="button" asp-action="List">回上一頁</a>
            </div>
        </form>
    </div>
</div>
<br />

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
@section Scripts {

    <script>
        const fileInput = document.getElementById('Photo');

        const previewImage = document.getElementById('preview-image');

        fileInput.addEventListener('change', event => {
            if (fileInput.files.length > 0) {
                const fileReader = new FileReader();

                fileReader.onload = function handleLoad() {
                    previewImage.src = fileReader.result;

                    previewImage.style.display = 'block';
                };

                fileReader.readAsDataURL(fileInput.files[0]);
            }

            // 👇️ reset file input once you're done
            //fileInput.value = null;
        });

        "use strict";

        function AJAXSubmit(oFormElement) {
            var oReq = new XMLHttpRequest();
            oReq.onload = function (e) {
                oFormElement.elements.nameItem("result").value =
                    'Result:' + this.status + '' + this.statusText;
            };
            oReq.open("post", oFormElement.action);
            oReg.send(new FormData(oFormElement));
        }

    </script>
}