prjFunShare_backend/Controllers/ManagerProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using prjFunShare_backend.Models;

namespace prjFunShare_backend.Controllers
{
    public class ManagerProductDetailController : Controller
    {
        private readonly FUNShareContext _context;
        public ManagerProductDetailController(FUNShareContext c)
        {
            _context = c;
        }
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult Create(int pid)
        {
            ViewBag.StatusId = new SelectList(_context.Status.Where(s => s.StatusType.Equals("ProductDetaill")), "StatusId", "Description");
            ViewData["DistrictId"] = new SelectList(_context.District, "DistrictId", "DistrictName");
            ProductDetail detail = new ProductDetail();
            detail.ProductId = pid;
            return View(detail);
        }
        [HttpPost]
        public IActionResult Create(ProductDetail p)
        {
            _context.ProductDetail.Add(p);
            _context.SaveChanges();
            //return Content("Created ProductDetais.");
            return RedirectToAction("Create", "ManagerPhoto", p.ProductId);
        }
        public IActionResult Edit(int id)
        {
            ViewBag.StatusId2 = new SelectList(_context.Status.Where(s => s.StatusType.Equals("Product_Detail")), "StatusId", "Description");
            ViewBag.DistrictId = new SelectList(_context.District, "DistrictId", "DistrictName");
            ProductDetail p = _context.ProductDetail.Find(id);
            ProductDetailWrap pd = new ProductDetailWrap();
            pd.productDetail = p;
            //ProductDetail pd = _context.ProductDetail.Find(id);
            return View(pd);
        }
        [HttpPost]
        public IActionResult Edit(ProductDetail p)
        {
            ProductDetail productDetail = _context.ProductDetail.Find(p.ProductDetailId);
            productDetail.BeginTime = p.BeginTime;
            productDetail.EndTime = p.EndTime;
            productDetail.DistrictId = p.DistrictId;
            productDetail.StatusId = p.StatusId;
            productDetail.Address = p.Address;
            productDetail.Stock = p.Stock;
            productDetail.UnitPrice = p.UnitPrice;
            productDetail.Dealine = p.Dealine;
            productDetail.ClassId = p.ClassId;
            _context.SaveChanges();
            return RedirectToAction("Edit", "SuperProduct", new { id = p.ProductId });

        }
        public IActionResult List(int pid)
        {
            var data = _context.ProductDetail.Where(p => p.ProductId == pid);
            return View(data);
        }
    }
}

prjFunShare_backend/Views/ManagerProductDetail/Create.cshtml
@model prjFunShare_backend.Models.ProductDetailWrap

@{
    ViewData["Title"] = "新增產品明細";
}

<h1>新增產品明細</h1>

<h4>產品明細</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @*  <div class="form-group">
                <label asp-for="ProductDetailId" class="control-label"></label>
                <input asp-for="ProductDetailId" class="form-control" />
                <span asp-validation-for="ProductDetailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="BeginTime" class="control-label"></label>
                <input asp-for="BeginTime" class="form-control" />
                <span asp-validation-for="BeginTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DistrictId" class="control-label"></label>
                <input asp-for="DistrictId" class="form-control" />
                <span asp-validation-for="DistrictId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <input asp-for="StatusId" class="form-control" />
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dealine" class="control-label"></label>
                <input asp-for="Dealine" class="form-control" />
                <span asp-validation-for="Dealine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            </br>
            <div class="form-group">
                <input type="submit" value="儲存" class="btn btn-primary" />
                <a class="btn btn-primary" type="button" asp-controller="ManagerProductDetail" asp-action="Create">繼續新增課程明細</a>
                <a class="btn btn-primary" type="button" asp-controller="ManagerPhoto" asp-action="DragandDrop">新增圖片</a>
            </div>
        </form>
    </div>
</div>
</br>
<div>
    <a asp-controller="ManagerProduct"  asp-action="List">回到產品首頁</a>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prjFunShare_backend/Views/ManagerProductDetail/Edit.cshtml
@model prjFunShare_backend.Models.ProductDetailWrap

@{
    ViewData["Title"] = "編輯產品明細";
}

<h1>編輯課程明細</h1>

<h4>課程明細</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="ProductDetailId" value="@Model.ProductDetailId" />
            <input type="hidden" name="ProductID" value="@Model.ProductId" />
            <div class="form-group">
                <label asp-for="BeginTime" class="control-label"></label>
                <input asp-for="BeginTime" class="form-control" />
                <span asp-validation-for="BeginTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DistrictId" class="control-label"></label>
                <select asp-for="DistrictId" class="form-control" value="17" asp-items="ViewBag.DistrictId"></select>
                <span asp-validation-for="DistrictId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" value="17" asp-items="ViewBag.StatusId2"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dealine" class="control-label"></label>
                <input asp-for="Dealine" class="form-control" />
                <span asp-validation-for="Dealine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="儲存" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@* <div>
    <a asp-controller="SuperProduct" asp-action="Edit"  >Back to List</a>
</div> *@

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

prjFunShare_backend/Views/ManagerProductDetail/List.cshtml
@model IEnumerable<prjFunShare_backend.Models.ProductDetail>

@{
    ViewData["Title"] = "課程明細一覽表";
}

<h1>課程明細總覽</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                序
            </th>
            <th>
                產品ID
            </th>
            <th>
                開始時間
               @*  @Html.DisplayNameFor(model => model.BeginTime) *@
            </th>
            <th>
                結束時間
                @* @Html.DisplayNameFor(model => model.EndTime) *@
            </th>
            <th>
                行政區編號
               @*  @Html.DisplayNameFor(model => model.DistrictId) *@
            </th>
            <th>
                狀態編號
                @* @Html.DisplayNameFor(model => model.StatusId) *@
            </th>
            <th>
                課程地址
                @* @Html.DisplayNameFor(model => model.Address) *@
            </th>
            <th>
                單價
                @* @Html.DisplayNameFor(model => model.UnitPrice) *@
            </th>
            <th>
                截止日期
              @*   @Html.DisplayNameFor(model => model.Dealine) *@
            </th>
            <th>
                教室編號
                @* @Html.DisplayNameFor(model => model.ClassId) *@
            </th>
            <th>編輯/刪除</th>
            <th>詳細資料</th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 0;
            foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>
                        @count
                    </td>
             <td>
                 @Html.DisplayFor(modelItem => item.ProductId)
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DistrictId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dealine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassId)
            </td>
            <td>
                        <a href="@Url.Action("DetailList" , "ManagerProduct", new { pid=item.ProductDetailId , id=item.ProductId })" class="btn btn-success">
                         <i class="fa-solid fa-list-check"></i>
                    </a>
            </td>
        </tr>
}}
    </tbody>
</table>